name: Android CI
 
on:
  push:
    branches: [ "master", "develop" ]
  pull_request:
    branches: [ "master" ]
 
jobs:
  build:
    runs-on: ubuntu-latest
 
    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v4
 
      - name: Configurar Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
 
      - name: Dar permisos a Gradle
        run: chmod +x gradlew
 
      - name: Compilar proyecto
        run: ./gradlew build
 
      - name: Ejecutar pruebas
        run: ./gradlew test
 
      - name: Generar APK debug
        run: ./gradlew assembleDebug
 
      - name: Guardar APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: app/build/outputs/apk/debug/*.apk
